name: shivansh_quantum_it
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
     
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0 
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_slidable: ^3.1.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animated/
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
